# Default recipes for Zig projects (seeded by `capsule init zig`).

default:
    @just --list

build:
    zig build

release:
    zig build -Doptimize=ReleaseFast

run *args:
    zig build run -- {{args}}

test:
    zig build test

lint:
    zig fmt --check src build.zig

clean:
    rm -rf zig-out zig-pkg .zig-cache
